[[manager.prepend_keymap]]
on = ["g"]
run = "arrow -99999999"

[[manager.prepend_keymap]]
on = ["<Tab>"]
run = "forward"
# <tab> & <c-i>
[[manager.prepend_keymap]]
on = ["<C-o>"]
run = "back"

[[manager.prepend_keymap]]
on = ["<F2>"]
run = "quit"
[[manager.prepend_keymap]]
on = ["<F3>"]
run = "quit"

[[manager.prepend_keymap]]
on = ["<F1>"]
run = """shell --confirm 'setsid -f $TERMINAL >/dev/null 2>&1'"""
[[manager.prepend_keymap]]
on = ["<Enter>"]
run = """shell --confirm 'setsid -f $TERMINAL >/dev/null 2>&1'"""

[[manager.prepend_keymap]]
on = ["e"]
run = "plugin zoxide"
[[manager.prepend_keymap]]
on = ["E"]
run = "plugin fzf"



[[input.prepend_keymap]]
on   = ["<Esc>"]
run  = "close"
desc = "cancel input"
