[manager]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
scrolloff = 0

[preview]
tab_size = 8
max_width = 10000
max_height = 10000

[opener]
fallback = [
	{run = 'firefox "$@"'},
]

[open]
prepend_rules = [
	{name = "*/", use = ["open"]},
	# {name = "*", use = ["open", "fallback"]},
]
append_rules = [
]

[tasks]

[plugin]
# prepend_fetchers = [
# 	{id = "git", name = "*", run = "git"},
# 	{id = "git", name = "*/", run = "git"},
# ]
# append_fetchers = [
# ]
prepend_previewers = [
	{mime = "text/x-diff",            run = "code"},
	{mime = "text/*",                 run = "head-and-expand"},
	{mime = "application/javascript", run = "head-and-expand"},
]
append_previewers = [
	{name = "*", run = "hexyl"},
]

[input]
# find_origin = "bottom-left"

[select]

[which]

[log]

[headsup]
