[manager]
ratio = [1, 2, 3]
sort_by = "natural"
show_hidden = true
scrolloff = 0

[preview]
tab_size = 8
max_width = 10000
max_height = 10000

[opener]

[open]

[tasks]

[plugin]
prepend_previewers = [
	{mime = "text/*", run = "preview-text"},
	{mime = "application/javascript", run = "preview-text"},
]

[input]
# find_origin = "bottom-left"

[select]

[which]

[log]

[headsup]
