[manager]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
scrolloff = 0

[preview]
tab_size = 8
max_width = 10000
max_height = 10000

[opener]
fallback = [
	{run = 'firefox "$@"'},
]

[open]
prepend_rules = [
	{name = "*/", use = ["open"]},
	# {name = "*", use = ["open", "fallback"]},
]
append_rules = [
]

[tasks]

[plugin]
prepend_previewers = [
	{mime = "text/*", run = "preview-text"},
	{mime = "application/javascript", run = "preview-text"},
]

[input]
# find_origin = "bottom-left"

[select]

[which]

[log]

[headsup]
