format = '[\($hostname $username $directory\)( \($git_branch$git_status\)) ](blue)'

add_newline = false

[hostname]
format = '$hostname'
ssh_only = false

[username]
format = '$user'
show_always = true

[directory]
format = '$path'
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '$branch'

[git_status]
format = '( $ahead_behind)( $all_status)'
